version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.5.6
    networks:
      - internet
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/hotrod_metrics_logs.json:/etc/grafana/provisioning/dashboards/hotrod_metrics_logs.json
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    depends_on:
      - loki

  loki:
    image: grafana/loki:master
    networks:
      - internet
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    # send Loki traces to Jaeger
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'


  tempo:
    image: grafana/tempo:latest
    networks:
      - internet
      - lognet
    command: ["-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    depends_on:
      - loki

  otel-collector:
    image: otel/opentelemetry-collector:0.32.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - internet
      - lognet
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    depends_on:
      - tempo
      - loki


  jaeger-agent:
    image: jaegertracing/jaeger-agent
    networks:
      - lognet
    command: ["--reporter.grpc.host-port=otel-collector:14250"]
    restart: on-failure
    depends_on:
        - otel-collector
        - loki

  hotrod:
    image: jaegertracing/example-hotrod:latest
    networks:
      - internet
      - lognet
    ports:
      - '8080:8080'
      - '8083:8083'
    command: ["-m","prometheus","all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus
    networks:
      - lognet
      - internet
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    depends_on:
      - loki

networks:
  default:
    name: intranet
    internal: true # restricts internet access
  lognet:
  internet:
    driver: bridge


